## Numpy

In [2]:
import numpy as np

arr_1d = np.array([1,2,3,4])
print("1d array :", arr_1d)
print(type(arr_1d))


arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("2d array :", arr_2d)
print(type(arr_2d))


1d array : [1 2 3 4]
<class 'numpy.ndarray'>
2d array : [[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


## Operation time

In [6]:
import time

start = time.time()

py_list = [i*2 for i in range(100000)]
print("/n Time taken for operation ",time.time() - start)    

start = time.time()
np_array = np.arange(100000) * 2
print("/n Time taken for operation ",time.time() - start)    


/n Time taken for operation  0.009023666381835938
/n Time taken for operation  0.0025529861450195312


## creating np from scratch

In [ ]:
zeros = np.zeros((1,2))
print(zeros)


ones = np.ones((1,2))
print(ones)

full = np.full((2,3) ,5)
print(full)

random = np.random.random((1,2))*10
print(random)

seq_arr = np.arange(0,31,3)
print(seq_arr)


[[0. 0.]]
[[1. 1.]]
[[5 5 5]
 [5 5 5]]
[[7.14129667 8.20151021]]
[ 1  4  7 10 13 16 19 22 25 28]


## vector, matrix & tensor

In [26]:
vector = np.array([1,2,3])
print("vector :",vector)


matrix = np.array([
                    [1,2,3],
                    [1,2,3]
                ])
print("matrix :",matrix)


tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print("tensor :",tensor)


vector : [1 2 3]
matrix : [[1 2 3]
 [1 2 3]]
tensor : [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


### Array properties

In [27]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape :",arr.shape)
print("Dimension :",arr.ndim)
print("Size :",arr.size)
print("Data type :",arr.dtype)


Shape : (2, 3)
Dimension : 2
Size : 6
Data type : int64


### Array Reshaping

In [37]:
arr = np.arange(12)
print(arr)

reshaped_arr = arr.reshape(3,4)
print(reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

transpose = reshaped_arr.T
print(transpose)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Sorting

In [ ]:
arr_1D = np.array([5,1,6,3,9,10])
sorted_1D_arr = np.sort(arr_1D)
print(sorted_1D_arr)

arr_2D = np.array([[1,2,4],[5,3,2]])
print("sorted 2D :",np.sort(arr_2D,axis=0)) # axis=0 for column

[ 1  3  5  6  9 10]
sorted 2D : [[1 2 4]
 [2 3 5]]


### Fliter

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = arr[arr % 2 != 0]
print(even_number)

[1 3 5 7 9]


## filter with mask

In [12]:
mask = arr > 5
print("Greater than 5:",arr[mask])

Greater than 5: [ 6  7  8  9 10]
