### Pandas Dataset

In [1]:
import pandas as pd
import numpy as np


arr = np.arange(0,20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Create Dataset

In [2]:
df = pd.DataFrame(data=arr,index=["Row1","Row2","Row3","Row4"],columns=["Col1","Col2","Col3","Col4","Col5",],)
print(df)

      Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19


In [3]:
df.head() # default 5 size of Dataframe size

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [4]:
df.tail() # defaut size = 5 last 5 Dataframe

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

## Type of DtaFrame

In [5]:
# type(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    4 non-null      int64
 1   Col2    4 non-null      int64
 2   Col3    4 non-null      int64
 3   Col4    4 non-null      int64
 4   Col5    4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


## Indexing

In [6]:
df.head()

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

In [7]:
df['Col1']   # type - pandas.core.series
# df[['Col1','Col2','Col3','Col4']]# type - pandas.core.DataFrame

Row1     0
Row2     5
Row3    10
Row4    15
Name: Col1, dtype: int64

In [8]:
df.loc[['Row1','Row4']]

Col1  Col2  Col3  Col4  Col5
Row1     0     1     2     3     4
Row4    15    16    17    18    19

In [9]:
#df.iloc[1:,1:3]
df.iloc[:,[0,3]] 

Col1  Col4
Row1     0     3
Row2     5     8
Row3    10    13
Row4    15    18

## DataFrame into arrays

In [10]:
df.iloc[:].values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
df['Col2'].value_counts()

Col2
1     1
6     1
11    1
16    1
Name: count, dtype: int64

In [12]:
df['Col3'].unique()

array([ 2,  7, 12, 17])

In [13]:
df[df['Col1']>2]

Col1  Col2  Col3  Col4  Col5
Row2     5     6     7     8     9
Row3    10    11    12    13    14
Row4    15    16    17    18    19

## Read a CSV File through Pandas

In [14]:
from io import StringIO
import pandas as pd
import numpy as py

df = pd.read_csv('mercedesbenz.csv')
df.head()
# print(type(df))

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

## Make String into File format Data through StringIO

In [15]:
data=('col1,col2,col3\n'
     'x,y,z\n'
     'a,b,c\n'
     'q,w,e\n')
type(data)#simple string

str

In [16]:
StringIO(data)
pd.read_csv(StringIO(data))

col1 col2 col3
0    x    y    z
1    a    b    c
2    q    w    e

## DataFame to csv file 

In [17]:
# df.to_csv('test.csv',index=False)
df.to_csv('test1.csv') #index=false means no need to add index number 0,1,2

## Datatype

In [18]:
data=('col1,col2,col3\n'
     'x,y,z\n'
     'a,b,c\n'
     'q,w,e\n'
     '1,2')
df=pd.read_csv(StringIO(data),dtype='object')



In [19]:
df.info() 
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      object
 1   col2    4 non-null      object
 2   col3    3 non-null      object
dtypes: object(3)
memory usage: 228.0+ bytes


col1    0
col2    0
col3    1
dtype: int64

In [22]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'q,w,3\n'
     '1,2,4')
df=pd.read_csv(StringIO(data),dtype={'col1':str,'col2':str,'col3':float})

In [23]:
df.info() 
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    4 non-null      object 
 1   col2    4 non-null      object 
 2   col3    4 non-null      float64
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes


col1    0
col2    0
col3    0
dtype: int64